
services:
  # 1. Database
  # mongo:
  #   image: mongo:latest
  #   container_name: mango-mongo
  #   restart: always
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - mango-net

  # 2. Backend (Go)
  backend:
    build: ./backend
    container_name: mango-backend
    restart: always
    environment:
      - MONGO_URI=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RADIUS_SERVER_ADDR=${RADIUS_SERVER_ADDR}
      - RADIUS_SECRET=${RADIUS_SECRET}
    # depends_on:
    #   - mongo
    networks:
      - mango-net

  # 3. Frontend (Next.js)
  # frontend:
  #   build: ./frontend
  #   container_name: mango-frontend
  #   restart: always
  #   networks:
  #     - mango-net

  # 4. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: mango-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - frontend
      - backend
    networks:
      - mango-net

volumes:
  mongo_data:

networks:
  mango-net: